import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/Navbar';
import { auth } from '@/auth';

import SessionProvider from "@/components/AuthProvider";



const inter = Inter({ subsets: ['latin'] });


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default  async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth()
  return (
    <html lang='en'>
      <body
        className={`${inter.className} antialiased`}
      >
        <SessionProvider session={session} >
          <div className='min-h-screen bg-gray-50'>
            <Navbar />
            <main className='container mx-auto px-4 py-8'>{children}</main>
          </div>
        </SessionProvider>
      </body>
    </html>
  );
}
